[project]
name = "rag-against-the-machine"
version = "0.1.0"
description = "A Retrieval-Augmented Generation system for querying the vLLM codebase."
requires-python = ">=3.10"

dependencies = [
    "fire",
    "pydantic",
    "tqdm",
    "rank-bm25",
    "transformers",
    "torch==2.9.1",
]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
    "pytest",
]